//
// Created by Elyas EL IDRISSI on 26/03/2021.
//

#ifndef INFINITECONQUEST_GLOBALTEXTUREMANAGER_H
#define INFINITECONQUEST_GLOBALTEXTUREMANAGER_H

#include "Manager/TextureManager.h"
extern TextureManager tm;

#endif //INFINITECONQUEST_GLOBALTEXTUREMANAGER_H
