//
// Created by Elyas EL IDRISSI on 27/03/2021.
//

#ifndef INFINITECONQUEST_GLOBALFAMILIARENTITYFACTORY_H
#define INFINITECONQUEST_GLOBALFAMILIARENTITYFACTORY_H


#include "Factory/FamiliarEntityFactory.h"
extern FamiliarEntityFactory fef;


#endif //INFINITECONQUEST_GLOBALFAMILIARENTITYFACTORY_H
