//
// Created by Elyas EL IDRISSI on 26/03/2021.
//

#ifndef INFINITECONQUEST_GLOBALENEMYENTITYFACTORY_H
#define INFINITECONQUEST_GLOBALENEMYENTITYFACTORY_H

#include "Factory/EnemyEntityFactory.h"
extern EnemyEntityFactory eef;

#endif //INFINITECONQUEST_GLOBALENEMYENTITYFACTORY_H
